name:                shlack
version:             0.1.0.0
github:              githubuser/shlack
license:             BSD3
author:              Alex Haynes & Robert Zajac
maintainer:          example@example.com
copyright:           2017 Alex Haynes & Robert Zajac

extra-source-files:
- README.md

# Metadata used when publishing your package
synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/shlack#readme>

dependencies:
- base >= 4.7 && < 5
- network
- split

library:
  source-dirs: lib
  dependencies:
    - ansi-terminal
    - containers
    - bytestring
    - transformers >= 0.5.2.0

executables:
  client:
    main:                Main.hs
    source-dirs:         client
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - shlack

  server:
    main:                Main.hs
    source-dirs:         server
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - shlack

tests:
  shlack-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - shlack
    - containers
    - HUnit
